# BART Makefile for T2 Shuffling recon

# Additional targets
TOPT= jtsense rjtsense te_proj te_mask te_prep
MODULES_te_prep = -ljtsense -lsense -liter -llinops
MODULES_jtsense = -ljtsense -lsense -lwavelet2 -lnoncart -llowrank -liter -llinops
MODULES_rjtsense = -ljtsense -lsense -lwavelet2 -lnoncart -llowrank -liter -llinops
MODULES_bart += -ljtsense

XTARGETS += $(TOPT)
