# BART Makefile for T2 Shuffling recon

# Additional targets
TOPT= jtsense rjtsense t2sh_proj t2sh_mask t2sh_prep
MODULES_t2sh_prep = -ljtsense -lsense -liter -llinops
MODULES_jtsense = -ljtsense -lsense -lwavelet2 -lnoncart -llowrank -liter -llinops
MODULES_rjtsense = -ljtsense -lsense -lwavelet2 -lnoncart -llowrank -liter -llinops
MODULES_bart += -ljtsense

XTARGETS += $(TOPT)
